### ISSUE TITLE
prediction 

### ISSUE THREAD

**Issue by No2rmal** [Nguyendat-bit/U-net#1]
Hello I am using your code to create a neural network model.
After creating the model I want to make a prediction and I get the following message:

(base) E:\python\U-net-main>python predict.py --test-file 0_1_0.png --image-size 512
---------------------Welcome to Unet-------------------
Author
Github: Nguyendat-bit
Email: nduc0231@gmail
---------------------------------------------------------------------
Predict Unet model with hyper-params:
===========================
0.model_save: Unet.h5
1.test_file: 0_1_0.png
2.image_size: 512
3.color_mode: hsv
4.function: None
5.use_kmean: True
Traceback (most recent call last):
  File "E:\python\U-net-main\predict.py", line 36, in <module>
    Mean_IoU = m_iou(args.classes)
AttributeError: 'Namespace' object has no attribute 'classes'

I can't figure out what the error is. Can you help me?

**Comment by Nguyendat-bit** [comment]
hi @No2rmal, thank u very much for this report, I made a quick fix for this problem.
